// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.panda.domain;

import com.test.panda.domain.Positions;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Positions_Roo_Jpa_Entity {
    
    declare @type: Positions: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Positions.id;
    
    @Version
    @Column(name = "version")
    private Integer Positions.version;
    
    public Long Positions.getId() {
        return this.id;
    }
    
    public void Positions.setId(Long id) {
        this.id = id;
    }
    
    public Integer Positions.getVersion() {
        return this.version;
    }
    
    public void Positions.setVersion(Integer version) {
        this.version = version;
    }
    
}
