// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.panda.domain;

import com.test.panda.domain.SelectCandidate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect SelectCandidate_Roo_Jpa_Entity {
    
    declare @type: SelectCandidate: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long SelectCandidate.id;
    
    @Version
    @Column(name = "version")
    private Integer SelectCandidate.version;
    
    public Long SelectCandidate.getId() {
        return this.id;
    }
    
    public void SelectCandidate.setId(Long id) {
        this.id = id;
    }
    
    public Integer SelectCandidate.getVersion() {
        return this.version;
    }
    
    public void SelectCandidate.setVersion(Integer version) {
        this.version = version;
    }
    
}
