// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.panda.domain;

import com.test.panda.domain.SelectCandidate;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SelectCandidate_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager SelectCandidate.entityManager;
    
    public static final List<String> SelectCandidate.fieldNames4OrderClauseFilter = java.util.Arrays.asList("");
    
    public static final EntityManager SelectCandidate.entityManager() {
        EntityManager em = new SelectCandidate().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long SelectCandidate.countSelectCandidates() {
        return entityManager().createQuery("SELECT COUNT(o) FROM SelectCandidate o", Long.class).getSingleResult();
    }
    
    public static List<SelectCandidate> SelectCandidate.findAllSelectCandidates() {
        return entityManager().createQuery("SELECT o FROM SelectCandidate o", SelectCandidate.class).getResultList();
    }
    
    public static List<SelectCandidate> SelectCandidate.findAllSelectCandidates(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM SelectCandidate o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, SelectCandidate.class).getResultList();
    }
    
    public static SelectCandidate SelectCandidate.findSelectCandidate(Long id) {
        if (id == null) return null;
        return entityManager().find(SelectCandidate.class, id);
    }
    
    public static List<SelectCandidate> SelectCandidate.findSelectCandidateEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM SelectCandidate o", SelectCandidate.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<SelectCandidate> SelectCandidate.findSelectCandidateEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM SelectCandidate o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, SelectCandidate.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void SelectCandidate.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void SelectCandidate.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            SelectCandidate attached = SelectCandidate.findSelectCandidate(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void SelectCandidate.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void SelectCandidate.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public SelectCandidate SelectCandidate.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        SelectCandidate merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
